### ISSUE TITLE
Making Location a Filter

### ISSUE THREAD

**Issue by operationadopt** [cferdinandi/fetch-bugs#17]
We are not able to have 2 petfinder accounts at this time for 2 locations (in different states).  The workaround we figured out is to have Location show as a filter.  With petfinder, we are able to choose a name for a 2nd location, but the first location shows ups as the default location.  We need to create a Location Filter and have the text for the default location read Burbank, California and the text for the second location read Friendsville, Tennessee.  

I read the instructions but I can't figure out if the template items will stay the same and I just need to add this somewhere - plus I am not sure what to add.  

Willing to pay for help with this.

We use squarespace.

**Comment by cferdinandi** [comment]
This is not possible, as the new Petfinder API does not return location data.
