### ISSUE TITLE
Not Displaying Pets

### ISSUE THREAD

**Issue by lfbox7** [cferdinandi/fetch-bugs#22]
I just purchased this product under the email: adm1n@lytleanimalallies.org. Our site is running WordPress v5.0.3.

Page:
https://lytleanimalallies.org/adopt/

Shortcode (there is an api key being used):
[fetch key="" shelter="tx1318"  count="50"]

As the page loads, the initial loading message appears but none of our pets are loaded. 

The <div> fetch-container is built, but only the Petfinder and documentation links are displayed on the page.

**Comment by cferdinandi** [comment]
Your shelter ID is incorrect. It needs to be all caps: `TX1318`
