### ISSUE TITLE
Link to PetFinder.com Listing

### ISSUE THREAD

**Issue by the18** [cferdinandi/fetch-bugs#23]
Is there a way I can change the "adoptionformlink" to have a link directly to the pet on Petfinder.com? Not sure if that's an item you can pull from the Petfinder api, but would save some time and need for customizing a form.

Second question would be whether there is a way to perhaps pull the name of the animal into the "adoptionformlink" and "adoptionformtext" to customize those, and maybe send a querystring to a form on our site for pre-population.

**Comment by cferdinandi** [comment]
These are all very good questions! Let met dig into the source code a bit and get back to you.

**Comment by cferdinandi** [comment]
Good news/bad news.

Good news is, the next version of Fetch will support this.

The bad news is, the new Petfinder API does not provide full text descriptions for pets, so the only option is to link each pet to its petfinder page.
