### ISSUE TITLE
Petfinder API 2.0 Support

### ISSUE THREAD

**Issue by icbfranz** [cferdinandi/fetch-bugs#24]
Hello,

Do you support the new API that Petfinder has pushed out? I have updated my API key and Fetch does not work. I have to read the documentation to see if SSL image pull is finally a part of this.

**Comment by cferdinandi** [comment]
No firm plans on this yet. I am considering it but not ready to commit one way or the other. It would involve a bit rewrite of the codebase.

I checked and SSL is *still* not supported, which is insanely frustrating. 😞

**Comment by snyders08** [comment]
Any update on your decision?

**Comment by cferdinandi** [comment]
Sorry for the lack of response here. I have a new version almost complete, powered by the new Petfinder API.

Customers will be getting an email as soon as it goes live.
