### ISSUE TITLE
Hiding Filter Breeds 

### ISSUE THREAD

**Issue by snyders08** [cferdinandi/fetch-bugs#25]
For some reason when I set the filterBreeds option to false it is hiding every animal. The other filter options are working as intended just this one is not working.

**Comment by cferdinandi** [comment]
Is this with the new Fetch v2?

**Comment by snyders08** [comment]
Yes it is.

[cid:image001.png@01D59DED.3EBE3340]
Donald Snyders
donald@babinskifoundation.org<mailto:donald@babinskifoundation.org>
Babinski Properties & The Babinski Foundation
(218) 568-2100 ext. 105

**Comment by cferdinandi** [comment]
@snyders08 I just released a fix for this. You can download the updated files using the same download link that was included in your purchase confirmation email, or by creating an account at https://courses.gomakethings.com/join using the same email you used to make your purchase.
