### ISSUE TITLE
Fetch 2 options not working for me

### ISSUE THREAD

**Issue by gwenski** [cferdinandi/fetch-bugs#27]
I am using the new Fetch 2 as a Wordpress plugin. I got my new API key and secret code from Petfinder and I can see all of the animals fine. However none of the options are working for me. I have tried multiple options but none seem to work. All of the filters are always displayed. Here is my current simplified code:

[fetch2 key="##############" secret="###########"  shelter="CO###" showfilters="false"]
[/fetch2]

I have tried this in multiple browsers so I do not believe it is a browser cache issue. I did notice that in the first Wordpress example your closing tag is [/fetch] and in the second Wordpress example the closing tag is [/fetch2]. I tried both with no difference in behavior.

**Comment by cferdinandi** [comment]
If you want to hide the filters, `showfilters` should be `true`. Good catch on the closing tags. I'll update the documentation accordingly.

**Comment by cferdinandi** [comment]
Nope I’m an idiot. I’ll look into this ASAP.

**Comment by cferdinandi** [comment]
@gwenski - thanks for this. You found a bug I didn't know about.

I just pushed an updated version of the plugin that fixes the "no options" bug. If you download a fresh copy, and update your plugin, this should work as expected. Sorry for the trouble!

**Comment by gwenski** [comment]
Thanks for fixing this Chris. It's working fine now. I think you still have
an extra bit of code in your $markup variable for debugging purposes
(<pre>...</pre>.

Gwen

**Comment by cferdinandi** [comment]
Ah shoot! In my effort to push this out the door I forgot to remove some debugging code. Just pushed _another_ updated version that removes that. So sorry!
