### ISSUE TITLE
Support for a new google hosted site

### ISSUE THREAD

**Issue by aalbina-git** [cferdinandi/fetch-bugs#28]
I'm helping some friends with their new dog rescue - definitely a labor of love!  They've setup their initial site on the new google sites and domain name from goDaddy (http://www.motleymuttsrescue.com)

The really want to use your plugin - do you know if it will work on google sites?  Do you have any other folks using google sites?

Thanks for the help.

Adam

**Comment by cferdinandi** [comment]
I've never tested it, but it looks like Google Sites now supports embeded code (including JavaScript), so... _probably_?

https://gsuiteupdates.googleblog.com/2017/12/embed-html-and-javascript-in-new-google-sites.html

Worst case scenario: you try it, it doesn't work, I give you a full refund.

**Comment by aalbina-git** [comment]
OK – I’ll give it a try and if I can get it to work I will send you the steps I took for your future customers.  It’s not a gsuite site but the standard site which also allows embedding of javascript.  What I can’t do is upload the *.js file and the *.css file to the site and then include the standard links in the html source.  I may have to put all of the js/css in line in the html doc.  I’ll let you know.

Adam

--
Adam R. Albina, PhD
Assistant Professor
Computer Science Department
Saint Anselm College
100 Saint Anselm Drive
Manchester, NH 03102
aalbina@anselm.edu<mailto:aalbina@anselm.edu>
603.641.7574
