### ISSUE TITLE
Continually loading

### ISSUE THREAD

**Issue by jackiegrob** [cferdinandi/fetch-bugs#29]
Hello, We use the Fetch plugin on our website. Right now it is continually saying "loading" and nothing is happening, it won't load. The website's server (Wix) is not down either and Petfinder is working. Do you have any ideas on what this could be and how we could fix it?

**Comment by cferdinandi** [comment]
If you can share a link to the site, I’ll take a look

**Comment by jackiegrob** [comment]
thank you so much. I am not technical at all and my husband is the one who
set everything up and he's unreachable right now.

www.aliverescue.org

if you click "adopt" you should see it!

Jackie Groberski, CFA
Development Director, ALIVE Rescue
www.aliverescue.org

**Comment by jackiegrob** [comment]
You know what I think I figured it out. I believe we hit our limit for the
day of inquiries. I THINK that's what it is. I'm going to call them again
and confirm.

Jackie Groberski, CFA
Development Director, ALIVE Rescue
www.aliverescue.org
