### ISSUE TITLE
Pets not displaying 

### ISSUE THREAD

**Issue by icbfranz** [cferdinandi/fetch-bugs#30]
Hello,

We have recently had an issue with Fetch. It is not displaying all the pets and in some instances none of them at all. Our API is not hitting max usage so that is not the problem. When using `limit` I can get pets to display when setting `limit: 10 `but when set to 0 it should show all pets. But nothing is shown.

Some context. We have three locations. Only one location has a problem. Here is a rundown: 
https://www.sthuberts.org/adoptable-animals-madison - Does not show pets (NJ04)
https://www.sthuberts.org/adoptable-animals-north-branch - shows (NJ09)
https://www.sthuberts.org/adoptable-animals-noahs-ark - shows (NJ860)
 
Reached out to Petfinder they are able to call NJ04. Attached is the API output they received. 
[api_test.txt](https://github.com/cferdinandi/fetch-bugs/files/4589880/api_test.txt)

**Comment by cferdinandi** [comment]
It appears as though the page where the pets are not showing numerous JavaScript errors on the page. One of them is likely stopping the rest of the scripts from running.

I tested your initialization locally and everything is working.

It also looks like your version of Fetch is a version of two behind on some bug fixes. You can create an account using the email used for purchase and download the latest version here: https://courses.gomakethings.com
