### ISSUE TITLE
Add option to replace missing/unfound image

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/fetch-bugs#6]

**Comment by DCSiira** [comment]
Could you provide an example of how to specifically use this tag?
 noimage: 'fetch/catdog.jpg',

I'm having difficulties having it find the image. Thank you

**Comment by cferdinandi** [comment]
Hey there! It should point to the specific URL for the image, which would vary from site to site.

If you, for example, added the image `catdog.jpg` to the `fetch` directory and uploaded that to the root directory for your site, you would use:

```js
fetch.init({
    key: "YOUR API KEY",
    shelter: "YOUR SHELTER ID",
    noImage: 'http://your-website.com/fetch/catdog.jpg'
});
```

You have to point to the exact URL of the image you want to use. You should also make sure that `noImage` is camel-case (the `i` in `Image` is uppercase) and not lowercase.

**Comment by cferdinandi** [comment]
Ignore what I posted above. This is a not-yet-supported feature that somehow made it way into the documentation.

**Comment by cferdinandi** [comment]
Coming in fetch v2.
