### ISSUE TITLE
Possible to add listing of placed pets?

### ISSUE THREAD

**Issue by loneoak** [cferdinandi/fetch-bugs#7]
fetch with squarespace (everything is working fine for available pets)

Is it possible to show a page with our placed pets? (how?)

Thx!

**Comment by cferdinandi** [comment]
I'll flag this as a feature request. It would require the ability to specify the adoption status, which the plugin currently does not support but the Petfinder API does.

**Comment by cferdinandi** [comment]
This is coming in Fetch 2, powered by the new Petfinder API.
